apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-og5a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-og5a
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-og5a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-og5a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-og5a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wggz-tenant/rhtap-demo-app/hacbs-test-project-og5a@sha256:d762d235302d50a6aa39938751dbdab8b99f222139b98385c4051650a6eba7fb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
